// thư viện
import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";

// thêm từ các component
import NextAuthProvider from "./(client)/_nextauth/NextAuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
