// thư viện
import type { Metadata } from "next";
import "./globals.css";
import 'suneditor/dist/css/suneditor.min.css';

// thêm từ các component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from "./providers";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
      <body>
        <ToastContainer position="bottom-left" autoClose={2000} />
        <Providers >
          {children}
        </Providers>
      </body>
    </html>
  )
}
